name: Run Telegram Trading Bot

on:
  schedule:

    # 9:20 AM IST
    - cron: "50 3 * * 1-5"

    # Every 5 minutes till 3:30 PM IST
    - cron: "*/5 4-10 * * 1-5"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance
          pip install requests
          pip install pytz

      - name: Run trading bot
        run: python telegram_bot.py
